/* SPDX-License-Identifier: MPL-2.0 */

package io.ulalax.zlink;

public enum SocketOption {
    AFFINITY(4), ROUTING_ID(5), SUBSCRIBE(6), UNSUBSCRIBE(7),
    RATE(8), RECOVERY_IVL(9), SNDBUF(11), RCVBUF(12),
    RCVMORE(13), FD(14), EVENTS(15), TYPE(16), LINGER(17),
    RECONNECT_IVL(18), BACKLOG(19), RECONNECT_IVL_MAX(21),
    MAXMSGSIZE(22), SNDHWM(23), RCVHWM(24), MULTICAST_HOPS(25),
    RCVTIMEO(27), SNDTIMEO(28), LAST_ENDPOINT(32),
    ROUTER_MANDATORY(33), TCP_KEEPALIVE(34), TCP_KEEPALIVE_CNT(35),
    TCP_KEEPALIVE_IDLE(36), TCP_KEEPALIVE_INTVL(37), IMMEDIATE(39),
    XPUB_VERBOSE(40), IPV6(42), PROBE_ROUTER(51), CONFLATE(54),
    ROUTER_HANDOVER(56), TOS(57), CONNECT_ROUTING_ID(61),
    HANDSHAKE_IVL(66), XPUB_NODROP(69), BLOCKY(70),
    XPUB_MANUAL(71), XPUB_WELCOME_MSG(72), INVERT_MATCHING(74),
    HEARTBEAT_IVL(75), HEARTBEAT_TTL(76), HEARTBEAT_TIMEOUT(77),
    XPUB_VERBOSER(78), CONNECT_TIMEOUT(79), TCP_MAXRT(80),
    MULTICAST_MAXTPDU(84), USE_FD(89), REQUEST_TIMEOUT(90),
    REQUEST_CORRELATE(91), BINDTODEVICE(92),
    TLS_CERT(95), TLS_KEY(96), TLS_CA(97), TLS_VERIFY(98),
    TLS_REQUIRE_CLIENT_CERT(99), TLS_HOSTNAME(100),
    TLS_TRUST_SYSTEM(101), TLS_PASSWORD(102),
    XPUB_MANUAL_LAST_VALUE(98), ONLY_FIRST_SUBSCRIBE(108),
    TOPICS_COUNT(116), ZMP_METADATA(117);

    private final int value;
    SocketOption(int v) { this.value = v; }
    public int getValue() { return value; }
}
